### ISSUE TITLE
When there is nothing left to validate, show 0

### ISSUE THREAD

**Issue by frodrigo** [teritorio/clearance-frontend#129] opened 2024-05-08 16:16 UTC
When there is nothing left to validate, show 0. Missing value look ugly and prone to question.

**Comment by wazolab** [comment] 2024-05-13 07:59
Duplicate of #114 no ?

**Comment by frodrigo** [comment] 2024-05-13 08:01
No, this one about the missing value here

![image](https://github.com/teritorio/clearance-frontend/assets/1785486/0c017348-3976-4706-9764-15cbd8569ba3)

**Closed** 2024-05-13 09:27 UTC
